export const ADD_USER = 'ADD_USER';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const OPEN_PUBLISH = 'OPEN_PUBLISH';
export const LOGIN = 'LOGIN';
export const OPEN_LOGIN='OPEN_LOGIN'
export const SUBMIT_ARTICLE='SUBMIT_ARTICLE'
export const SELECT_CARD='SELECT_CARD'
export const OPEN_COMPOSE='OPEN_COMPOSE'
export const OPEN_HOME='OPEN_HOME'
export const CLOSE_LOGIN='CLOSE_LOGIN'
export const CLOSE_HOME='CLOSE_HOME'
export const CLOSE_COMPOSE='CLOSE_COMPOSE'
export const DELETE='DELETE'
export const EDIT='EDIT'
export const EDIT_STATE='EDIT_STATE'