export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const SELECT_CARD = 'SELECT_CARD'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const CANCEL_SELECT = "CANCEL_SELECT"
export const ADD_COMMENT_TO_SPECIFIC_ARTICLE = 'ADD_COMMENT_TO_SPECIFIC_ARTICLE'
export const DELETE_COMMENT_FROM_SPECIFIC_ARTICLE = 'DELETE_COMMENT_FROM_SPECIFIC_ARTICLE'

