export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const SUBMIT_ARTICLE = 'SUBMIT_ARTICLE'
export const SELECT_CARD = 'SELECT_CARD'
export const DELETE = 'DELETE'
export const CANCEL_SELECT ="CANCEL_SELECT"
export const UPDATE_COMMENT='UPDATE_COMMENT'

